import localFont from "next/font/local";
import '@/Styles/Typography.css';
import '@/output.css';

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Payppy2.0",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest:"/manifest.json",
  keywords:["nextjs","next14","pwa","next-pwa"],
 viewport: "width=device-width, initial-scale=1.0",
 icons:[
  {rel:"apple-touch-icon", url: "/icons/icon-512.png" },
  {rel:"icon", url: "/icons/icon-512.png" },
 ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <link rel="manifest" href="/manifest.json"/>
      <link rel="icon" href="/icons/icon-512.png"/>
      <link rel="apple-touch-icon" href="/icons/icon-512.png"/>
    </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
